INSERT INTO employees(id, name) VALUES (1, 'Penny')
INSERT INTO employees(id, name) VALUES (2, 'Sheldon')
INSERT INTO employees(id, name) VALUES (3, 'Amy')
INSERT INTO employees(id, name) VALUES (4, 'Leonard')
INSERT INTO employees(id, name) VALUES (5, 'Bernadette')
INSERT INTO employees(id, name) VALUES (6, 'Raj')
INSERT INTO employees(id, name) VALUES (7, 'Howard')
INSERT INTO employees(id, name) VALUES (8, 'Priya')
